-- Extracted Snowflake SQL: 01_ingestion.sql

USE DATABASE AMAZON_REVIEWS_DB;
USE SCHEMA RAW;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE STAGE AMAZON_STAGE
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

LIST @AMAZON_STAGE;

CREATE OR REPLACE TABLE REVIEWS_RAW (
    ID NUMBER,
    PRODUCTID VARCHAR,
    USERID VARCHAR,
    PROFILENAME VARCHAR,
    HELPFULNESSNUMERATOR NUMBER,
    HELPFULNESSDENOMINATOR NUMBER,
    SCORE NUMBER,
    TIME NUMBER,
    SUMMARY VARCHAR,
    TEXT VARCHAR
);

COPY INTO REVIEWS_RAW
FROM @AMAZON_STAGE
FILE_FORMAT = (FORMAT_NAME = 'AMAZON_CSV_FORMAT')
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE FILE FORMAT AMAZON_CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

SELECT COUNT(*) AS ROW_COUNT
FROM REVIEWS_RAW;

SELECT * FROM REVIEWS_RAW LIMIT 20;
