-- Extracted Snowflake SQL: 02_cleaning_transform.sql

USE DATABASE AMAZON_REVIEWS_DB;
USE WAREHOUSE COMPUTE_WH;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE ANALYTICS.REVIEWS_CLEAN AS
SELECT
    r.ID                         AS REVIEW_ID,
    r.PRODUCTID                  AS PRODUCT_ID,
    r.USERID                     AS USER_ID,
    r.PROFILENAME                AS PROFILE_NAME,
    r.HELPFULNESSNUMERATOR       AS HELPFUL_YES,
    r.HELPFULNESSDENOMINATOR     AS HELPFUL_TOTAL,
    IFF(r.HELPFULNESSDENOMINATOR > 0,
        r.HELPFULNESSNUMERATOR / r.HELPFULNESSDENOMINATOR::FLOAT,
        0
    )                            AS HELPFUL_RATIO,
    r.SCORE                      AS RATING,
    TO_DATE(TO_TIMESTAMP_NTZ(r.TIME)) AS REVIEW_DATE,
    r.SUMMARY                    AS SUMMARY,
    r.TEXT                       AS REVIEW_TEXT
FROM RAW.REVIEWS_RAW r
WHERE r.SCORE BETWEEN 1 AND 5              
  AND r.HELPFULNESSNUMERATOR >= 0
  AND r.HELPFULNESSDENOMINATOR >= r.HELPFULNESSNUMERATOR
  AND r.TEXT IS NOT NULL;

SELECT COUNT(*) AS ROW_COUNT
FROM ANALYTICS.REVIEWS_CLEAN;

SELECT *
FROM ANALYTICS.REVIEWS_CLEAN
LIMIT 20;

SELECT COUNT(*) AS NULL_PRODUCT_ID
FROM ANALYTICS.REVIEWS_CLEAN
WHERE PRODUCT_ID IS NULL;

SELECT RATING, COUNT(*) AS N_REVIEWS
FROM ANALYTICS.REVIEWS_CLEAN
GROUP BY RATING
ORDER BY RATING;

CREATE OR REPLACE TABLE ANALYTICS.PRODUCT_METRICS AS
SELECT
    PRODUCT_ID,
    COUNT(*)                         AS N_REVIEWS,
    AVG(RATING)                      AS AVG_RATING,
    AVG(HELPFUL_RATIO)               AS AVG_HELPFUL_RATIO
FROM ANALYTICS.REVIEWS_CLEAN
GROUP BY PRODUCT_ID;

CREATE OR REPLACE TABLE ANALYTICS.USER_METRICS AS
SELECT
    USER_ID,
    COUNT(*)           AS N_REVIEWS,
    AVG(RATING)        AS AVG_USER_RATING,
    AVG(HELPFUL_RATIO) AS AVG_USER_HELPFUL_RATIO
FROM ANALYTICS.REVIEWS_CLEAN
GROUP BY USER_ID;

CREATE OR REPLACE TABLE ANALYTICS.DAILY_RATINGS AS
SELECT
    REVIEW_DATE,
    COUNT(*)      AS N_REVIEWS,
    AVG(RATING)   AS AVG_DAILY_RATING
FROM ANALYTICS.REVIEWS_CLEAN
GROUP BY REVIEW_DATE;
